$(document).ready(function(){
    let images = [
        { 
            src: "images/Alpaca.jpeg", 
            caption: "A - for Alpaca", 
            aiPrompt: "A high-quality image of an alpaca"
        },
        { 
            src: "images/Hat.jpg", 
            caption: "H - for Hat", 
            aiPrompt: "A high-quality image of a stylish hat"
        },
        { 
            src: "images/Mountain.jpg", 
            caption: "M - for Mountain", 
            aiPrompt: "A scenic image of a mountain landscape"
        },
        { 
            src: "images/Airplane.jpg", 
            caption: "A - for Airplane", 
            aiPrompt: "A clear image of an airplane flying in the sky"
        },
        { 
            src: "images/Desk.jpg", 
            caption: "D - for Desk", 
            aiPrompt: "An organized desk setup in a modern office"
        },
        { 
            src: "images/Astronaut.jpg", 
            caption: "A - for Astronaut", 
            aiPrompt: "An astronaut in their space suit"
        },
        { 
            src: "images/Keyboard.jpg", 
            caption: "K - for Keyboard", 
            aiPrompt: "A close-up of a computer keyboard with soft lighting"
        },
        { 
            src: "images/Bear.jpg", 
            caption: "B - for Bear", 
            aiPrompt: "A high-quality image of a bear in the forest"
        },
        { 
            src: "images/Aquarium.jpg", 
            caption: "A - for Aquarium", 
            aiPrompt: "A beautiful image of an aquarium with colorful fish"
        },
        { 
            src: "images/Rose.jpg", 
            caption: "R - for Rose", 
            aiPrompt: "A close-up of a red rose in full bloom"
        },
        { 
            src: "images/IceCream.jpg", 
            caption: "I - for Ice Cream", 
            aiPrompt: "An artistic photo of a cup with scoops of ice cream"
        }
    ];
    
    let currentIndex = 0;

    function loadSlide(index) {
        $("#slide-img").fadeOut(400, function() {
            $(this).attr("src", images[index].src).attr("alt", images[index].caption).fadeIn(400);
            $("#caption").text(images[index].caption);
            $("#ai-caption").text("Generated by AI: \"" + images[index].aiPrompt + "\"");
        });
        currentIndex = index;
    }

    $("#image-nav a").click(function(e) {
        e.preventDefault();
        let index = $(this).data("index");
        loadSlide(index);
    });

    loadSlide(currentIndex); 
});